### PR TITLE
NCMesh HowTo article [howto-ncmesh]

### PR DESCRIPTION
**Pull request by jakubcerveny**
Adds HowTo article to address https://github.com/mfem/mfem/issues/2321

### CODE REVIEW

**Comment by jakubcerveny** [comment]
I think this is ready for review.

I general, I have some suggestions for the changes in the `searchable-articles` branch:

* I would keep the top main menu as is (Features, Examples, Documentation, Gallery, Download). Examples are still the main resource on how to use various MFEM features and I don't think they deserve to be filed under "Small Examples". The word "small" is misleading, they are small by design, as they usually demonstrate a single feature.

* "Getting Started" can be its own page, accessible as the first item under "Documentation", and it can contain a list of links to introductory articles like "Building MFEM" etc.

* If there are too many items in "Documentation", some of them can also be grouped under "link pages", as in "Getting Started" above.

* HowTo articles should have a link page as well, where the articles are sorted in categories. HowTo articles is a great idea IMO, but having them accessible only through Search is insufficient -- they would be practically hidden.

* "Topic Search" is good, but could use some kind of differentiation from other items in the "Documentation" menu. Maybe putting it last, or add an ellipsis ("Search..."), or even better, a magnifying glass icon in the top menu?

* The search page is good but the text could use some copy-editing, e.g., "various topics" in the headline sounds suspicious to me, and the description should be simplified and streamlined. Can we make the example keywords gray inside the edit box before one starts typing ("Example: nonlinear")?

**Comment by tzanio** [comment]
Thanks @jakubcerveny!

I very much agree with your suggestions... @acfisher, what do you think?

**Comment by acfisher** [comment]
I like the Idea of pulling the topic search into the top of the page with a magnifying glass.  I'll see if I can do that.

I'll also look into greyed out example keywords in the text box, I'm worried it might trigger the very limited search system, but we'll see.

I think adding links to article through the page will be valuable, but I don't like to idea of maintaining a topic sorted landing page (or page hierarchy)  for all of the HowTo articles.  Sure that would be easy with the ~10 articles we have, but what happens when we have 200?

**Comment by acfisher** [comment]
The work on the NC Mesh article is excellent!  Thanks for putting it together!

**Review by acfisher — APPROVED** [review]
Thanks for the excellent work.  I'll pull it in.

**Comment by jakubcerveny** [comment]
If the articles had categories somehow assigned to them (with some HTML tag?), the list of all howto articles could be generated with some script...

**Pull request merged**
