### PR TITLE
Example 37 updated figure

### PR DESCRIPTION
**Pull request by brendankeith**
I'm updating the figure and equation formatting for example 37

### CODE REVIEW

**Comment by tzanio** [comment]
Thanks @brendankeith.

The GIF is very cool, but at 11MB it makes the examples page even heavier to load.

What do you think about keeping the old static image but make it a link to the GIF?

Tzanio

**Comment by brendankeith** [comment]
> Thanks @brendankeith.
> 
> The GIF is very cool, but at 11MB it makes the examples page even heavier to load.
> 
> What do you think about keeping the old static image but make it a link to the GIF?
> 
> Tzanio

Ah, good point. I now have it down to 871 KB, which looks about the same. Would it make sense to replace the gifs instead? (The old static image was 386 KB.)

**Comment by tzanio** [comment]
I like it, thanks!

How did you compress it?

**Comment by brendankeith** [comment]
> I like it, thanks!
> 
> How did you compress it?

Thanks for the quick merge!

I made a completely new GIF using lower-resolution PNGs from ParaView.

**Pull request merged**
