### PR TITLE
Implement video thumbnail link format

### PR DESCRIPTION
**Pull request by hauten**
**Changes in this PR:**
- Closes https://github.com/mfem/web/issues/257
- Changes YouTube link format to reference YT's auto-generated high-res thumbnail images instead of embedding the video on the page
- Links the new thumbnails to the YT videos
- Replaces 7 auto-generated thumbnails with custom screen shots
- Adds new directory for custom thumbnails (`img/videos/`)

**Link syntax:**
- Auto-generated thumbnail: `[](https://www.youtube.com/watch?v=**YouTubeID**)`
- Custom thumbnail: `[](https://www.youtube.com/watch?v=WJ5dAhOR6Gg)`

**Create a custom thumbnail when the auto-generated thumbnail:** 
- Doesn't exist (e.g., a video several years old)
- Is the wrong aspect ratio (e.g., a video several years old)
- Doesn't show any part of the speaker's talk (e.g., shows a screen from the animated MFEM logo intro)
- Has too much white background and/or doesn't stand out on the web page

### CODE REVIEW

**Comment by hauten** [comment]
Example from my local (Qi's thumbnail is custom; Jamie's & Veselin's are auto-generated): 
image

**Comment by tzanio** [comment]
Thanks for doing this @hauten, it is a great improvement!

I was concerned that people may not recognize the images as videos so I added an overlay play button and some hover-over interaction in this branch: https://github.com/mfem/web/tree/video-thumbs-tk. 

Here are the diffs with your PR (the play button image, a bit of CSS and HTML image specification): https://github.com/hauten/web/compare/video-thumbs...mfem:video-thumbs-tk

_What do you think?_

I also noticed that Tamas Horvath's thumbnail still shows an image from the MFEM logo intro. Is that intentional?

**Comment by hauten** [comment]
@tzanio I must have just missed Tamas's thumbnail. I'll make one for it. The "play" icon looks good. The .jpg and .png HTML is missing the closing > tag, so I'm adding that. Fingers crossed that I can successfully commit to your branch, stay tuned!

**Comment by hauten** [comment]
image

**Comment by hauten** [comment]
OK well I committed here. But I had pulled in `video-thumbs-tk` and everything looks good locally.

**Comment by hauten** [comment]
Before (left) and after (right)
image

**Comment by tzanio** [comment]
Looks great, thank you so much @hauten !

**Pull request merged**
