### PR TITLE
Modify website header

### PR DESCRIPTION
**Pull request by tzanio**
### Updates to the navigation bar:

- Allow for more tabs/menu items (but also collapse sooner)
- New `Outreach` tab with links to the `Videos`, `Seminar`, `Workshop` and `Publications` pages
- Updated `LESS -> CSS` build instructions

Screen Shot 2022-03-04 at 7 18 50 PM

### CODE REVIEW

**Review by jandrej — APPROVED** [review]

**Review by jakubcerveny — APPROVED** [review]
I think this is OK, I'm just wondering if we should drop some of the older navbar items to make the navbar less overloaded, perhaps the "Download" item, because there already is a large download button on the page and an "Older releases" link? Also most people now just clone the library from GitHub...

**Comment by tzanio** [comment]
>  I'm just wondering if we should drop some of the older navbar items to make the navbar less overloaded, 

I agree this will be good. One option is to shorten "Documentation" to "Docs".

> perhaps the "Download" item, because there already is a large download button on the page and an "Older releases" link? Also most people now just clone the library from GitHub...

I added the versioned docs there, so it is still useful to have IMHO. Also, it is probably better to call that item "Releases" now.

**Comment by kmittal2** [comment]
Some ideas to consider:
- Combine the `Features` and `Documentation` Tabs into something like `About` or `Info` (or something else)? 
- Replace `Download` with something like &#x2193; and put it on the right side besides GitHub?

**Review by kmittal2 — APPROVED** [review]

**Comment by tzanio** [comment]
Screen Shot 2022-03-24 at 2 24 18 PM

☝️  **Before | After** 👇 

Screen Shot 2022-03-24 at 2 24 10 PM

---

Screen Shot 2022-03-24 at 2 25 13 PM

☝️  **Before | After** 👇 

Screen Shot 2022-03-24 at 2 25 21 PM

**Pull request merged**
