### PR TITLE
Website changes for mfem-4.4

### PR DESCRIPTION
**Pull request by tzanio**
### TODO
- [x] Switch version to 4.4
- [x] Updated contributors
- [x] Update publications
- [x] Address #160
- [x] Address #166

### Optional 
- [ ] Address #154
- [ ] Address #164
- [ ] Address #165

### CODE REVIEW

**Review by victorapm — APPROVED** [review]
Thank you, @tzanio!

**Comment by sebastiangrimberg** [comment]
Thanks a lot @tzanio! You can use: [Sebastian Grimberg](https://scholar.google.com/citations?user=p2FEptUAAAAJ&hl=en).

**Review by sebastiangrimberg — APPROVED** [review]
Thanks a lot @tzanio!

**Comment by wo80** [comment]
Thank you, @tzanio!

**Review by brendankeith — APPROVED** [review]
Glad to finally be part of the club! Thanks!

**Pull request merged**
