### PR TITLE
MFEM Community Workshop

### PR DESCRIPTION
**Pull request by acfisher**
Add a page describing the upcoming community workshop.

### CODE REVIEW

**Comment by hauten** [comment]
The table had 4 columns on some rows so I removed those. Added a sentence about WebEx info being distributed later (I assume).

**Comment by acfisher** [comment]
@hauten Thanks for the edits!

**Comment by hauten** [comment]
After seeing the full registration form, I made one more commit to add a note about submitting a talk, etc. with the same deadline as registration.
image

**Review by tzanio — APPROVED** [review]
Ready to go from my perspective.

*Thanks @acfisher and @hauten!*

**Review by hauten — APPROVED** [review]

**Pull request merged**
