### PR TITLE
Better navigational context

### PR DESCRIPTION
**Pull request by tzanio**
(Potentially) Resolves https://github.com/mfem/web/issues/134

### CODE REVIEW

**Comment by tzanio** [comment]
Here is one possible approach to improve navigation based on this comment in #134 

> Alternatively, I wonder if the right-side nav within a page (where the page's headings are listed) could be modified to include a link back to the parent page.

Screen Shot 2021-09-11 at 3 34 00 PM

We can add more conditions based e.g. on the page title.

The CEED website uses this method to both add "Contact CEED" info on each page, e.g. https://ceed.exascaleproject.org/about/ as well as for a special set of info links on the main page, https://ceed.exascaleproject.org/. See https://github.com/CEED/web/blob/master/template/toc.html and https://github.com/CEED/web/blob/master/template/toc-home.html.

**Review by jakubcerveny — APPROVED** [review]
Looks good to me!

**Review by hauten — APPROVED** [review]
I like it!

**Comment by tzanio** [comment]
@hauten, Do you think we should add such a link to other pages? Right now it is applied only to the "HowTo" articles

**Comment by hauten** [comment]
I think it would be useful for the pages under Getting Started (link could say "Back to Getting Started").

**Comment by tzanio** [comment]
OK, how about the last commit?

Now you can just tag the articles and we have several base pages (can/should probably add more).

I deployed at mfem.org so you can test easier.

**Review by acfisher — APPROVED** [review]
This is an excellent addition.

**Comment by tzanio** [comment]
(Just merging, this is already deployed)

**Pull request merged**
