### PR TITLE
Spectral fractional PDE in MFEM

### PR DESCRIPTION
**Pull request by brendankeith**
This is the companion PR to https://github.com/mfem/mfem/pull/2832.

### CODE REVIEW

**Comment by brendankeith** [comment]
@tzanio I removed the conflicts with `master`. This is again ready for review.

**Comment by tzanio** [comment]
Thanks @brendankeith

**Review by brendankeith — COMMENTED** [review]
Approved!

**Review by tzanio — APPROVED** [review]
Thanks @brendankeith !

**Pull request merged**
