### PR TITLE
Navier miniapp description

### PR DESCRIPTION
**Pull request by jandrej**
I recycled the picture from the gallery but could add a different one.

### CODE REVIEW

**Comment by tzanio** [comment]
Can we use your profile picture instead?

Also, do you envision eventually having a page like https://mfem.org/electromagnetics/ with more details?

**Comment by jandrej** [comment]
Sure we can use my profile picture. I am not sure where to put a more detailed documentation. There was the idea floating around to write a technical report, but having it on a dedicated webpage is a good idea.

**Comment by tzanio** [comment]
It is up to you, but I personally think that a short Markdown page like https://raw.githubusercontent.com/mfem/web/master/src/electromagnetics.md is easier to write and may get more views than a tech report. You can just create a new file, say `src/navier.md` and add it to `mkdocs.yml`.

That doesn't mean you shouldn't write reports and papers :)

**Comment by v-dobrev** [comment]
Looks good!

One small issue I noticed is: when I click on the "Fluid" button under "Application (PDE)" -- only the Navier miniapp is shown (as expected) but there is also a message "No examples or miniapps match your criteria." after that which is unexpected.

**Comment by jandrej** [comment]
I noticed that too, I'm not sure what causes that.

**Comment by mlstowell** [comment]
There is a check in `examples.md` (around line 1468) which loops through the examples and checks to see if example `"ex"+num` is hidden.  If all of the examples are hidden it displays this message.  We need to also loop through a list of mini app names to check if these are hidden as well.  I'm not sure how to implement that but I'm fairly certain that's the problem.

**Comment by jandrej** [comment]
> There is a check in `examples.md` (around line 1468) which loops through the examples and checks to see if example `"ex"+num` is hidden. If all of the examples are hidden it displays this message. We need to also loop through a list of mini app names to check if these are hidden as well. I'm not sure how to implement that but I'm fairly certain that's the problem.

I'm going to try some things and see if I can make it work.

**Comment by jandrej** [comment]
I think the last commit might be a solution. @mlstowell @v-dobrev

**Comment by mlstowell** [comment]
@jandrej , can you also update the README.md file to mention this miniapp list in the "Checklist" portion at the end of the file.

Should we tag examples 9 and 18 with the new "fluid" label?

**Comment by mlstowell** [comment]
BTW:  I think this miniapp deserves its own page similar to `electromagnetic.md` as @tzanio suggested. It doesn't necessarily need to be part of this PR but it would be a great addition to the website.

**Comment by tzanio** [comment]
@jakubcerveny, can you take a quick look at 9b4ebe8?

**Comment by jakubcerveny** [comment]
I checked and it seems fine. 

While I was at, it I simplified the filtering code, so it should no longer be necessary to mess with the `numExamples` variable or similar. I'm thinking of more changes so there's a new PR based on this one: #58

**Comment by jakubcerveny** [comment]
Just one thing about this PR -- isn't the "Fluid" category too vague? Maybe it should read "Incompressible flow" or something like that? Or keep it as is, but include the compressible flow examples too? (Not sure, just thinking)

**Comment by jandrej** [comment]
@jakubcerveny @tzanio @mlstowell I merged the filtering PR from @jakubcerveny and there is one remaining point:

How to name the category?

* Fluids
* Incompressible flow
* Put it in hydro (not sure if accurate)
* Other suggestions welcome

**Comment by tzanio** [comment]
> How to name the category?

I have two suggestions:

1. Rename `Hydrodynamics` to `Compressible Flow` and put the new category under it as `Incompressible Flow`. 

2. Merge with `Hydrodynamics` and rename to `Flow`

**Comment by jandrej** [comment]
@jakubcerveny @mlstowell suggestions?

**Comment by jakubcerveny** [comment]
I think there are two options:
1. Since we already have categories like "Laplace" and "Darcy", we should maybe call the fluid flow ones "Euler" and "Navier-Stoker". The good thing is these are short.
2. But maybe it is more correct to use general names, so "Diffusion" instead of "Laplace" (is Laplace even correct, maybe it should be "Poisson"?), there already is "Elasticity", "Advection", etc., so add "Compressible flow", "Incompressible flow" and then "Meshing" at the end.

**Comment by jandrej** [comment]
Second option it is then.

**Pull request merged**
