### PR TITLE
Adding documentation for the new Linear Interpolators

### PR DESCRIPTION
**Pull request by tzanio**

### CODE REVIEW

**Comment by tzanio** [comment]
@mlstowell, now that https://github.com/mfem/mfem/pull/139 is merged should we also merge this in the `v3.4-dev` placeholder branch?

Let me know if you need any help finishing it up :)

**Comment by tzanio** [comment]
@mlstowell -- a reminder that this documentation is still not merged.

**Comment by mlstowell** [comment]
Thanks for the reminder @tzanio.  I had completely forgotten about this.

**Comment by tzanio** [comment]
Thanks for the quick reply @mlstowell!

**Comment by tzanio** [comment]
I "approve" this PR.

@mlstowell and @v-dobrev, can you confirm that you are OK with merging it in?

**Pull request merged**
