### PR TITLE
Adding 'tools.md' file to describe the miniapps/tools subdirectory [get-values-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
This started as documentation for the `get-values` miniapp but there are other tools that need to be described as well.

To start, I just copied the comment blocks from the head of each source file and made a few simple edits.

### CODE REVIEW

**Comment by mlstowell** [comment]
While attempting to generate a graphic for the `load-dc` miniapp I had trouble loading data from example 5 as described in [`load-dc.cpp`](
https://github.com/mfem/mfem/blob/67c195af60a345539275c5fc19ddc44df2fe6716/miniapps/tools/load-dc.cpp#L23).  This is a type of problem that probably wouldn't be caught by our regular testing so a bug may have crept in.  Was this miniapp written by @acfisher ?

**Comment by tzanio** [comment]
I believe @cyrush wrote `load-dc` and we recently had a PR fixing an issue there (https://github.com/mfem/mfem/pull/1209).

**Comment by cyrush** [comment]
extracting the load-dc text into the docs looks good to me.

**Comment by mlstowell** [comment]
Update on possible `load-dc` issue: Testing on quartz showed no problems at all.  Running on my MacBook produces the following error:
```
load-dc -r ../../examples/Example5
Options used:
   --root-file ../../examples/Example5
   --cycle 0
   --visualization
fields: [ pressure, velocity ]
Assertion failed in file src/mpi/misc/utils.c at line 55: FALSE
memcpy argument memory ranges overlap, dst_=0x7ffee7e31afe src_=0x7ffee7e31aff len_=4

internal ABORT - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
```
I'm willing to accept that this might be a problem with my local configuration.  If someone else could try this on a different Mac I would appreciate it.

Best wishes,
Mark

**Comment by mlstowell** [comment]
I added a simple example image produced by `load-dc`.  If anyone wants to provide a different image please feel free, as long as it's appropriate.

**Comment by v-dobrev** [comment]
This PR looks good to me.

The issue that Mark mentioned above (regarding the `load-dc` miniapp) should be resolved in https://github.com/mfem/mfem/pull/1242.

**Pull request merged**
