### PR TITLE
Fix some incorrect statements in the mesh format description

### PR DESCRIPTION
**Pull request by v-dobrev**
This PR is meant to address the issue https://github.com/mfem/mfem/issues/3094.

### CODE REVIEW

**Comment by v-dobrev** [comment]
@sethwatts, I invited you to the Contributors MFEM team, so you should be able to commit to this repo (the sources for the MFEM website) if you want to edit this PR directly. The Contributors team also gives you access to the main MFEM source repo, if you want to contribute there.

Let me know if you have any other recommendations for changes or additions.

**Comment by tzanio** [comment]
Is this ready for review?

**Comment by sethwatts** [comment]
> Is this ready for review?

I believe so.

**Comment by pazner** [comment]
Should a link to this page be added to the [mesh formats](https://mfem.org/mesh-formats/) page? I had trouble finding it on the website.

**Comment by v-dobrev** [comment]
> Should a link to this page be added to the [mesh formats](https://mfem.org/mesh-formats/) page? I had trouble finding it on the website.

It is linked already by the second link in the second bullet under "MFEM Mesh Formats", however, I also had trouble finding it, so I agree we need to make it more obvious, e.g. as a separate bullet for that page.

**Review by tzanio — APPROVED** [review]

**Review by pazner — APPROVED** [review]

**Pull request merged**
