### PR TITLE
Searchable articles

### PR DESCRIPTION
**Pull request by acfisher**
A little bit of reformatting of the website and addition of searchable howto articles.

### CODE REVIEW

**Comment by tzanio** [comment]
Overall this is a really nice improvement, thank you @acfisher!

A few issues and suggestions:

- In the middle size the menu is wrapped, which is not what we want... Any ideas how to fix that? Maybe we can consolidate some of the menu items in that specific case?

Screen Shot 2021-06-29 at 10 49 16 AM

- The [HowTo page](http://127.0.0.1:8000/search/) needs some work -- maybe we can provide some examples of search terms (e.g. "howto") and list the currently available HowTo articles? Also, this is searching more than the "HowTo Database"

- The rendering of some pages in the search is weird, e.g. search for "findpoints" or "_linear"

**Comment by acfisher** [comment]
I agree on all points.  I'm glad you caught the middle size problem.  Maybe if we group the miniapps in with the examples it will fit?

I'll get some instructions on there and open up the search to some more of the pages.  I'll also see what I can do about those misrendered articles.

**Comment by acfisher** [comment]
It's worth taking another look at this point.

**Review by jandrej — APPROVED** [review]
It looks like partial word searches are "premium feature" in MkDocs. All changes look reasonable.

**Comment by tzanio** [comment]
Definitely an improvement... I like the embedded Doxygen 😁

**Comment by acfisher** [comment]
Oh I didn't know that they actually support that.  Maybe it is worth considering going premium.

**Comment by acfisher** [comment]
I also plan to do a copy edit of all of the article going in.

**Comment by acfisher** [comment]
@tzanio @jakubcerveny Please have another look at let me know what you think about the new formatting and the HowTo Index page.

**Review by tzanio — APPROVED** [review]
This super-awesome thanks for making it happen @acfisher 🎉 🎉 🎉 

@jakubcerveny -- thanks for helping with the styling and the awesome HowTo page!

**Review by acfisher — COMMENTED** [review]
The latest changes look great.  Lets pull it in.

**Comment by acfisher** [comment]
Than you @pazner @YohannDudouit @kmittal2 @adrienbernede @jakubcerveny, and @tzanio for helping to make this happen.  I believe we have added a good resource for our users and I hope we keep adding articles in the future.

**Pull request merged**
