### PR TITLE
[WIP] Draft for adding documentation of nonlinear integrators

### PR DESCRIPTION
**Pull request by jandrej**
This is a proposed enhancement for the website to mention nonlinear integrators. I'd like to see someone else contribute some words for Hyperelasticity because I'm not familiar with the physics there.

We can also use the opportunity to clarify the essential boundary "effect" on the local action of the `NonlinearForm`.

### CODE REVIEW

**Comment by vladotomov** [comment]
I will add a short description of the TMOP integrator.

**Comment by tzanio** [comment]
Is this ready to go guys?

**Comment by vladotomov** [comment]
TMOP is ready, but the Hyperelasticity is still empty.

**Comment by tzanio** [comment]
Any objections to merge this as is? (We can add the Hyperelasticity section later when/if we have time)

**Review by tzanio — APPROVED** [review]
Merging this as is for now, though we should really improve this page as many users will be interested in it!

**Pull request merged**
