### PR TITLE
Documentation for miniapps/toys [toys-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
Creating a separate page for the documentation of the toys miniapps

Companion documentation for https://github.com/mfem/mfem/pull/847

### CODE REVIEW

**Comment by mlstowell** [comment]
To start I put a few simple static images.  I plan to create simple animated GIFs for `rubik` and `life`.  We'll also need to add a paragraph or two of text for each miniapp.

**Comment by mlstowell** [comment]
@tzanio , I think the basics are in place in `toys.md`.  I was thinking you might want to use the Klein bottle image for `mandel`.  I considered trying to create an animation for `lissajous` but it's a bit tricky because of how the image is updated in GLVis rather than being controlled from the mini app.  I can continue to pursue this unless you have a trick up your sleeve (or another suitable image in mind).

**Comment by tzanio** [comment]
> I can continue to pursue this unless you have a trick up your sleeve

Try `S` while spinning :)

**Comment by mlstowell** [comment]
@tzanio , your trick worked perfectly.  Thanks!

I think this is ready to go except for the `mandel` image.  Some of the miniapp descriptions are quite minimal.  Feel free to expand or replace any of the text as you see fit.

**Comment by tzanio** [comment]
I added a Mandel image and made a few changes (feel free to revert if you don't like them). I agree this will be ready to go once mfem/mfem#847 is merged. Thank you Mark!

**Pull request merged**
