### PR TITLE
Adding documentation for boundary condition example [bc-example-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
This is a companion PR for [PR #1357](https://github.com/mfem/mfem/pull/1357)

### CODE REVIEW

**Comment by mlstowell** [comment]
@tzanio, I think this PR is ready for feedback at least and hopefully for review.  It contains a lot more than just documentation for example 27 but I hope the extra pages will be useful.  Much of this documentation is inspired by things we've explained in various issues and things I've spoken to collaborators about in other forums.  Let me know if the technical level seems appropriate.  I tried to direct it towards FEM novices who should already be comfortable with vector calculus.

**Comment by tzanio** [comment]
Thanks @mlstowell! I'll take a look...

**Comment by tzanio** [comment]
Can you check my merge in 186692a?

**Review by tzanio — APPROVED** [review]
Thanks a lot @mlstowell -- the new pages are really great!

**Review by bslazarov — COMMENTED** [review]
Great additions!

**Pull request merged**
