### PR TITLE
Changes after mfem-3.4 release

### PR DESCRIPTION
**Pull request by tzanio**
TODO:
- [x] Add the entries from the `mfem.bib` file to `src/publications.md` -- @mlstowell 
- [x] Fix incorrect links to [Doxygen-generated class images](https://github.com/mfem/mfem/pull/487#issuecomment-391425117). Maybe come up with a better way to update these after a release? -- @tzanio
- [ ] Update/fix `CONTRIBUTING.md` with release process details (in a separate PR). 
- [x] Switch to latest MkDocs, see PR #9?
- [ ] Make the website even more awesome overall 🏆

### CODE REVIEW

**Comment by tzanio** [comment]
@mfem/developers -- please post below if you are taking on one of the TODO items above.

Also, feel free to add other suggestions for post-release website improvements.

**Comment by mlstowell** [comment]
I'll take care of the first TODO item.

**Comment by mlstowell** [comment]
Question for @tzanio.  Should there be a 1-1 correspondence between the entries in mfem.bib and the listing in publications.md?  I ask because I'v noticed some older entries in mfem.bib that do not appear in publications.md (and vice versa).  I'll be happy to bring these lists into complete agreement if this is what you want (I've built a small Perl script which helps considerably).

**Comment by tzanio** [comment]
@mlstowell wrote:
> Question for @tzanio. Should there be a 1-1 correspondence between the entries in mfem.bib and the listing in publications.md? I ask because I'v noticed some older entries in mfem.bib that do not appear in publications.md (and vice versa). I'll be happy to bring these lists into complete agreement if this is what you want (I've built a small Perl script which helps considerably).

Yes, both of these lists are supposed to represent papers that are using MFEM in some way in BibTeX and Markdown formats respectively, so having them synchronized will be ideal. If that is easy for you, consider also checking the following for items that may be missing from mfem.bib and/or publications.md:
- https://computation.llnl.gov/projects/blast/publications
- https://scholar.google.com/citations?hl=en&user=FYdIBi4AAAAJ&view_op=list_works&sortby=pubdate
- https://orcid.org/0000-0002-2810-3090
- http://ceed.exascaleproject.org/pubs/ (note that there are many non-MFEM references there)

Thanks so much for doing this Mark. I know it is tedious, but it is very important for the publicity of the project!

**Comment by mlstowell** [comment]
Tedium can be like meditation.

**Comment by tzanio** [comment]
I will take the second item.

**Comment by tzanio** [comment]
@mlstowell -- do you have any more publication-related changes or are we ready to check that box?

I cleaned them up a bit, but otherwise they look like a huge improvement (50 more entries!). Thanks!

**Pull request merged**
