### PR TITLE
Add Fischer seminar video

### PR DESCRIPTION
**Pull request by hauten**
Updated seminar title and video link on `seminar.md`. Added seminar info, abstract, and embedded YT player to `videos.md`. Also moved the `<div>` to keep FEM videos in two neat columns.

### CODE REVIEW

**Comment by hauten** [comment]
FYI something's wrong w/ the July seminar on `seminars.md`. On prod it's blank, but locally it shows the speaker's name, photo, & correct date.

image
image

**Review by v-dobrev — APPROVED** [review]
Tested locally -- looks good.

**Comment by v-dobrev** [comment]
Thanks @hauten! Feel free to merge and deploy, or if you prefer, let me know and I can do it.

**Comment by hauten** [comment]
> Thanks @hauten! Feel free to merge and deploy, or if you prefer, let me know and I can do it.

I'm not sure I know how to deploy...

**Comment by v-dobrev** [comment]
I merged and deployed this. Deploying is done with `mkdocs gh-deploy`. I typically also run `git clean -df site` before that to make sure I have a clean re-build deployed.

By the way, this added the missing picture for J. Banks, so that looks good now.

**Pull request merged**
